- hosts: localhost
  tasks:
  - name: Delete the application
    k8s
      state: present
      definition: "{{ lookup('file', 'delete_deployment.sh') }}"  
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'deployment.yml') | from_yaml }}"
